package org.example.model;

import jakarta.persistence.*;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.math.BigDecimal;
import java.util.Collection;
import java.util.List;

/**
 * This class represents a bank account.
 * It stores the user's login info, balance, transactions, and profile.
 */
// This class is the representation of a bank account
    // It stores the user login info, balance, transactions and profile
@Entity // Mark this class as a JPA entity that will be mapped to the database table
public class AccountModel implements UserDetails { // implement User Details from spring security for authentication

    // Unique ID for each account, auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-increments the ID
    private Long id;

    // User login details
    @Column(unique = true, nullable = false)
    private String username;

    // Password of the user
    private String password;

    // The user's current account balance
    private BigDecimal balance;

    // A user can have many transactions
    @OneToMany(mappedBy = "account", cascade = CascadeType.ALL)
    private List<Transaction> transactions; // all transactions associated with this account

    // A user has one profile (name, contact info, etc.)
    @OneToOne(mappedBy = "account", cascade = CascadeType.ALL)
    private ClientProfile clientProfile; // The User profile associated with this account

    // Roles or permissions for the user (not stored in the database)
    @Transient
    private Collection<? extends GrantedAuthority> authorities; // Roles/permissions, not stored in DB

    // Required default constructor
    public AccountModel() {} // Required by JPA

    // Optional constructor to create an account object directly
    public AccountModel(String username, String password, BigDecimal balance,
                        List<Transaction> transactions,
                        Collection<? extends GrantedAuthority> authorities) {
        this.username = username;
        this.password = password;
        this.balance = balance;
        this.transactions = transactions;
        this.authorities = authorities;
    }

    // --- Getters and Setters ---

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getUsername() { return username; }
    public void setUsername(String username) { this.username = username; }

    @Override
    public String getPassword() { return password; }
    public void setPassword(String password) { this.password = password; }

    public BigDecimal getBalance() { return balance; }
    public void setBalance(BigDecimal balance) { this.balance = balance; }

    public List<Transaction> getTransactions() { return transactions; }
    public void setTransactions(List<Transaction> transactions) { this.transactions = transactions; }

    public ClientProfile getClientProfile() { return clientProfile; }

    public void setClientProfile(ClientProfile clientProfile) {
        this.clientProfile = clientProfile;

        // Maintain bidirectional link from profile back to this account
        if (clientProfile != null) {
            clientProfile.setAccount(this);
        }
    }

    //  Spring Security Integration – UserDetails Methods

    public Collection<? extends GrantedAuthority> getAuthorities() { return authorities; }
    public void setAuthorities(Collection<? extends GrantedAuthority> authorities) {
        this.authorities = authorities;
    }

    // --- These methods are required by Spring Security ---

    @Override
    public boolean isAccountNonExpired() { return true; }

    @Override
    public boolean isAccountNonLocked() { return true; }

    @Override
    public boolean isCredentialsNonExpired() { return true; }

    @Override
    public boolean isEnabled() { return true; }
}
