package org.example.model;

import jakarta.persistence.*;
import java.time.LocalDate;


// This class stores the personal information of a client
    // Each profile belongs to one bank account
@Entity // // Marks this as a JPA entity for persistence.
public class ClientProfile {

    // Unique ID for each client profile (auto-generated by the database)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // Primary key for the client profile table.

    // ===== Personal Information =====
    private String firstName;
    private String lastName;
    private LocalDate dateOfBirth;
    private String nationalId;        // National ID (e.g., SSN or Passport)
    private String address;
    private String email;
    private String phone;
    private String employmentStatus;
    private Double annualIncome;
    private String profilePhotoPath;  // File path for profile photo (optional)

    // ===== Account Link =====
    // This connects the profile to one specific account
    @OneToOne
    @JoinColumn(name = "account_id") // This will create a column named account_id in the database
    private AccountModel account;

    // ===== Getters and Setters =====

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getFirstName() { return firstName; }
    public void setFirstName(String firstName) { this.firstName = firstName; }

    public String getLastName() { return lastName; }
    public void setLastName(String lastName) { this.lastName = lastName; }

    public LocalDate getDateOfBirth() { return dateOfBirth; }
    public void setDateOfBirth(LocalDate dateOfBirth) { this.dateOfBirth = dateOfBirth; }

    public String getNationalId() { return nationalId; }
    public void setNationalId(String nationalId) { this.nationalId = nationalId; }

    public String getAddress() { return address; }
    public void setAddress(String address) { this.address = address; }

    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }

    public String getPhone() { return phone; }
    public void setPhone(String phone) { this.phone = phone; }

    public String getEmploymentStatus() { return employmentStatus; }
    public void setEmploymentStatus(String employmentStatus) { this.employmentStatus = employmentStatus; }

    public Double getAnnualIncome() { return annualIncome; }
    public void setAnnualIncome(Double annualIncome) { this.annualIncome = annualIncome; }

    public String getProfilePhotoPath() { return profilePhotoPath; }
    public void setProfilePhotoPath(String profilePhotoPath) { this.profilePhotoPath = profilePhotoPath; }

    public AccountModel getAccount() { return account; }
    public void setAccount(AccountModel account) { this.account = account; }
}
