package org.example.model;

// Brings in the JPA annotations to map this class to a database table.
import jakarta.persistence.*;

// Used for handling money values accurately.
import java.math.BigDecimal;
// Used to store the date and time of each transaction.
import java.time.LocalDateTime;


// Representation of a financial transaction performed by a client
@Entity // Marks this class as a JPA entity (it will become a table in the database).
@Table(name = "transactions") // Explicitly maps this entity to the "transactions" table.
public class Transaction {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // Unique ID for each transaction. Auto-generated by the database.

    // Transaction amount which has to be a positive value
    private BigDecimal amount;

    // Type of transaction.
    private String type; // "DEPOSIT" or "WITHDRAWAL or Transfer In or Transfer Out"

    // It is a user entered reason why the user has made a deposit
    @Column(nullable = false)
    private String message; // this will be implemented to monitor why the user makes a deposit, why he/she makes a withdrawal and the reason for

    // When the transaction is executed
    private LocalDateTime timestamp;

    // Reference to the account model, that owns this transaction
    // Many transactions can only be linked to one account
    // One account can make multiple transactions
    @ManyToOne
    @JoinColumn(name = "account_id") // Foreign key to the AccountModel table.
    private AccountModel account;

    // Defualt constructor for JPA
    public Transaction() {}

    public Transaction(BigDecimal amount,String message, String type, LocalDateTime timestamp, AccountModel account) {
        this.amount = amount;
        this.type = type;
        this.timestamp = timestamp;
        this.account = account;
        this.message = message;
    }

    // Getters and Setters
    public String getMessage() {
        return message;
    }

    public void setMessage(String category) {
        this.message = category;
    }

    public Long getId() { return id; }

    public void setId(Long id) { this.id = id; }

    public BigDecimal getAmount() { return amount; }

    public void setAmount(BigDecimal amount) { this.amount = amount; }

    public String getType() { return type; }

    public void setType(String type) { this.type = type; }

    public LocalDateTime getTimestamp() { return timestamp; }

    public void setTimestamp(LocalDateTime timestamp) { this.timestamp = timestamp; }

    public AccountModel getAccount() { return account; }

    public void setAccount(AccountModel account) { this.account = account; }
}
